name: Database CI

on:
  pull_request:
    paths:
      - ".github/workflows/database-ci.yml"
      - "frontend/packages/db/**"
  merge_group:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pg_tap_tests:
    name: PGTap Tests
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: supabase/setup-cli@d347ba47d3fb7eeeddbbc793bc8d4779caf773ea # v1.5.0
        with:
          version: latest
      - name: Supabase Start
        run: supabase start
      - name: Setup supabase testing
        run: |
          psql -v ON_ERROR_STOP=1 -U postgres -d postgres -h localhost -p 54322 -f .github/workflows/setup-testing.sql
        env:
          PGPASSWORD: postgres
      - name: Run Tests
        run: supabase test db
