on:
  discussion_comment:
    types: [created]

jobs:
  discussion_commented:
    if: github.event.discussion && github.event.comment
    uses: route06/actions/.github/workflows/gh_discussion_comment_to_slack.yml@155715656c4cd9079f1213d08d058e78dd00cae7 # v2
    secrets:
      slack-webhook-url: ${{ secrets.SLACK_GHD_WEBHOOK_URL }}
