name: Figma to CSS Variables

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write # for actions/checkout, peter-evans/create-pull-request
  pull-requests: write # for peter-evans/create-pull-request

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/pnpm-setup
      - run: pnpm --filter @packages/figma-to-css-variables sync --output '../../apps/service-site/src/styles' --filter-modes "Dark,Mode 1"
        env:
          FIGMA_FILE_KEY: ${{ secrets.FIGMA_FILE_KEY }}
          FIGMA_ACCESS_TOKEN: ${{ secrets.FIGMA_ACCESS_TOKEN }}
      - uses: peter-evans/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e # v7.0.8
        with:
          commit-message: "maintenance: Sync Figma to CSS Variables"
          branch: "maintenance/sync-figma-to-css-variables"
          delete-branch: true
          title: "maintenance: Sync Figma to CSS Variables"
