name: License Report Update

# ## Summary
#
# This workflow updates $LICENSE_REPORT using license_finder CLI
# and automatically create a pull request if any changes are detected.

on:
  schedule:
    - cron: "00 0 * * 1" # every monday 9:00 JST
  workflow_dispatch:

jobs:
  license_report_update:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    timeout-minutes: 10
    env:
      LICENSE_REPORT: docs/packages-license.md
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Create GitHub App Token
        uses: actions/create-github-app-token@3ff1caaa28b64c9cc276ce0a02e2ff584f3900c5 # v2.0.2
        id: app-token
        with:
          app-id: ${{ vars.LICENSE_CI_TRIGGER_APP_ID }}
          private-key: ${{ secrets.LICENSE_CI_TRIGGER_APP_PRIVATE_KEY }}
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          token: ${{ steps.app-token.outputs.token }}
      - uses: ./.github/actions/pnpm-setup
      - uses: ruby/setup-ruby@f41e084df884422b269f4c01c3748a9df4431a75 # v1.236.0
        with:
          ruby-version: '3.4'
      - name: Install License Finder
        run: gem install -N license_finder
      - name: Generate license report
        run: |
          mkdir -p "$(dirname "$LICENSE_REPORT")"
          license_finder report --format=markdown | tail -n +2 > "$LICENSE_REPORT"
          # Delete the timestamp line because there will be a difference even if there is no change in licenses
          sed -e '/^As of /d' -i "$LICENSE_REPORT"
      - name: Create pull request if license report changes
        run: |
          if git diff --quiet; then
            echo 'No changes to commit'
            exit 0
          fi

          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'

          BRANCH_NAME="license-report-update-$(date +'%Y%m%d%H%M%S')"
          git checkout -b "$BRANCH_NAME"
          git add "$LICENSE_REPORT"
          git commit -m "Update $LICENSE_REPORT"
          git push origin "$BRANCH_NAME"
          gh pr create \
            --title "[$(date +'%Y/%m/%d')] License Report Update" \
            --body "This pull request automatically updates the license report."
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
