name: Notify Supabase Failure

on:
  check_suite:
    types: [completed]

jobs:
  notify_slack:
    runs-on: ubuntu-latest
    if: |
      github.event.check_suite.app.name == 'Supabase' &&
      github.event.check_suite.conclusion == 'failure'
      # github.event.check_suite.head_branch == 'main'
    steps:
      - name: Slack Notification for Supabase Failure
        uses: tokorom/action-slack-incoming-webhook@d57bf1eb618f3dae9509afefa70d5774ad3d42bf # v1.3.0
        env:
          INCOMING_WEBHOOK_URL: ${{ secrets.SLACK_CLI_CI_WEBHOOK_URL }}
        with:
          text: "Supabase Preview Deployment Failure"
          attachments: |
            [
              {
                "color": "bad",
                "fields": [
                  {
                    "title": "Branch",
                    "value": "main"
                  },
                  {
                    "title": "Check Suite App",
                    "value": "${{ github.event.check_suite.app.name }}"
                  },
                  {
                    "title": "Result",
                    "value": "failure"
                  },
                  {
                    "title": "Check Suite URL",
                    "value": "${{ github.event.check_suite.html_url }}"
                  }
                ]
              }
            ]
