name: release
on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions:
  actions: write # for `Trigger released_package_test.yml via API`
  id-token: write
  contents: write
  packages: write
  pull-requests: write
  issues: read

jobs:
  create_release_pull_request_or_publish:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Create GitHub App Token
        uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.CHANGESET_CI_TRIGGER_APP_ID }}
          private-key: ${{ secrets.CHANGESET_CI_TRIGGER_APP_PRIVATE_KEY }}

      - uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token }}
      - uses: ./.github/actions/pnpm-setup
      - name: Create Release Pull Request or Publish to npm
        id: changesets-action
        uses: changesets/action@v1.4.9
        with:
          publish: pnpm run release
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Trigger released_package_test.yml via API
        if: ${{ steps.changesets-action.outputs.published == 'true' }}
        run: |
          version=$(cat frontend/packages/cli/package.json | jq -r '.version')
          curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
               -H "Accept: application/vnd.github.v3+json" \
               https://api.github.com/repos/${{ github.repository }}/actions/workflows/released_package_test.yml/dispatches \
               -d '{"ref":"main", "inputs": { "delay_seconds": "60", "version": "'${version}'" }}'

      - name: Slack Notification on Failure
        if: failure()
        uses: tokorom/action-slack-incoming-webhook@d57bf1eb618f3dae9509afefa70d5774ad3d42bf # v1.3.0
        env:
          INCOMING_WEBHOOK_URL: ${{ secrets.SLACK_CLI_CI_WEBHOOK_URL }}
        with:
          text: "Release Failure"
          attachments: |
            [
              {
                "color": "bad",
                "fields": [
                  {
                    "title": "Result",
                    "value": "failure"
                  },
                  {
                    "title": "Job URL",
                    "value": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
                  }
                ]
              }
            ]
